name: zklogin
description: Sui zkLogin Dart SDK.
version: 0.0.3
homepage: https://github.com/mofalabs/zklogin

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  poseidon: ^0.0.1
  sui: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  dio: ^5.1.2
